version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8081:80'
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
